insert into clients (id, name, surname, email, created_at, photo) values (1, 'Lucas', 'Pérez', 'lucasper@hotmail.com','2018-08-28', '');
insert into clients (id, name, surname, email, created_at, photo) values (2, 'Maria', 'García', 'margar@gmail.com','2019-01-20', '');
insert into clients (id, name, surname, email, created_at, photo) values (3, 'Jorge', 'Felpeto', 'jorfel@gmail.com','2018-08-28', '');
insert into clients (id, name, surname, email, created_at, photo) values (4, 'Luis', 'Garconi', 'luigar@gmail.com','2016-03-24', '');
insert into clients (id, name, surname, email, created_at, photo) values (5, 'Ramon', 'Pantuflo', 'ramonpan@gmail.com','2015-01-21', '');
insert into clients (id, name, surname, email, created_at, photo) values (6, 'Maria', 'Pons', 'marpons@gmail.com','2014-05-15', '');
insert into clients (id, name, surname, email, created_at, photo) values (7, 'Rosa', 'Martinez', 'rosarmar@gmail.com','2018-08-12', '');
insert into clients (id, name, surname, email, created_at, photo) values (8, 'Juan', 'Fuentes', 'juanfue@gmail.com','2018-04-24', '');
insert into clients (id, name, surname, email, created_at, photo) values (9, 'Roberto', 'Perez', 'robper@gmail.com','2014-04-24', '');
insert into clients (id, name, surname, email, created_at, photo) values (10, 'Raquel', 'Olivera', 'raqol@gmail.com','2015-05-08', '');
insert into clients (id, name, surname, email, created_at, photo) values (11, 'Andres', 'Filon', 'andfil@hotmail.com', '2017-08-01', '');
insert into clients (id, name, surname, email, created_at, photo) values (12, 'John', 'Doe', 'john.doe@gmail.com', '2017-08-02', '');
insert into clients (id, name, surname, email, created_at, photo) values (13, 'Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2017-08-03', '');
insert into clients (id, name, surname, email, created_at, photo) values (14, 'Jane', 'Doe', 'jane.doe@gmail.com', '2017-08-04', '');
insert into clients (id, name, surname, email, created_at, photo) values (15, 'Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2017-08-05', '');
insert into clients (id, name, surname, email, created_at, photo) values (16, 'Erich', 'Gamma', 'erich.gamma@gmail.com', '2017-08-06', '');
insert into clients (id, name, surname, email, created_at, photo) values (17, 'Richard', 'Helm', 'richard.helm@gmail.com', '2017-08-07', '');
insert into clients (id, name, surname, email, created_at, photo) values (18, 'Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2017-08-08', '');
insert into clients (id, name, surname, email, created_at, photo) values (19, 'John', 'Vlissides', 'john.vlissides@gmail.com', '2017-08-09', '');
insert into clients (id, name, surname, email, created_at, photo) values (20, 'James', 'Gosling', 'james.gosling@gmail.com', '2017-08-010', '');
insert into clients (id, name, surname, email, created_at, photo) values (21, 'Bruce', 'Lee', 'bruce.lee@gmail.com', '2017-08-11', '');
insert into clients (id, name, surname, email, created_at, photo) values (22, 'Johnny', 'Doe', 'johnny.doe@gmail.com', '2017-08-12', '');
insert into clients (id, name, surname, email, created_at, photo) values (23, 'John', 'Roe', 'john.roe@gmail.com', '2017-08-13', '');
insert into clients (id, name, surname, email, created_at, photo) values (24, 'Jane', 'Roe', 'jane.roe@gmail.com', '2017-08-14', '');
insert into clients (id, name, surname, email, created_at, photo) values (25, 'Richard', 'Doe', 'richard.doe@gmail.com', '2017-08-15', '');
insert into clients (id, name, surname, email, created_at, photo) values (26, 'Janie', 'Doe', 'janie.doe@gmail.com', '2017-08-16', '');
insert into clients (id, name, surname, email, created_at, photo) values (27, 'Phillip', 'Webb', 'phillip.webb@gmail.com', '2017-08-17', '');
insert into clients (id, name, surname, email, created_at, photo) values (28, 'Stephane', 'Nicoll', 'stephane.nicoll@gmail.com', '2017-08-18', '');
insert into clients (id, name, surname, email, created_at, photo) values (29, 'Sam', 'Brannen', 'sam.brannen@gmail.com', '2017-08-19', '');  
insert into clients (id, name, surname, email, created_at, photo) values (30, 'Juergen', 'Hoeller', 'juergen.Hoeller@gmail.com', '2017-08-20', ''); 
insert into clients (id, name, surname, email, created_at, photo) values (31, 'Janie', 'Roe', 'janie.roe@gmail.com', '2017-08-21', '');
insert into clients (id, name, surname, email, created_at, photo) values (32, 'John', 'Smith', 'john.smith@gmail.com', '2017-08-22', '');
insert into clients (id, name, surname, email, created_at, photo) values (33, 'Joe', 'Bloggs', 'joe.bloggs@gmail.com', '2017-08-23', '');
insert into clients (id, name, surname, email, created_at, photo) values (34, 'John', 'Stiles', 'john.stiles@gmail.com', '2017-08-24', '');
insert into clients (id, name, surname, email, created_at, photo) values (35, 'Richard', 'Roe', 'stiles.roe@gmail.com', '2017-08-25', '');